"""Flow Library page — view and trigger agent-built Power Automate flows."""
import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

import json
import sqlite3
import streamlit as st
import pandas as pd

from config import DB_PATH

st.set_page_config(page_title="Flow Library", page_icon="⚡", layout="wide")
st.title("⚡ Flow Library")
st.caption("Power Automate flows generated by the agent — review, trigger, or build new ones")

if not DB_PATH.exists():
    st.warning("Database not initialised. Go to Admin → Setup.")
    st.stop()

# ── Build a flow manually ─────────────────────────────────────────────────────
with st.expander("Build a new flow", expanded=False):
    with st.form("new_flow_form"):
        flow_name = st.text_input("Flow Name", placeholder="e.g. Monthly Compliance Reminder")
        flow_desc = st.text_area("Description", placeholder="What does this flow do?")
        trigger = st.selectbox("Trigger", [
            "Scheduled (weekly)", "Scheduled (monthly)", "Scheduled (daily)",
            "Event: course_completed", "Manual trigger"
        ])
        actions_raw = st.text_area(
            "Actions (one per line)",
            placeholder="Query LMS for non-compliant employees\nSend Teams reminder\nLog to SharePoint",
        )
        submitted = st.form_submit_button("Create Flow", type="primary")

    if submitted and flow_name:
        try:
            from mcp_servers.automate_server import create_flow
            actions = [a.strip() for a in actions_raw.split("\n") if a.strip()]
            result = json.loads(create_flow(flow_name, flow_desc, trigger, json.dumps(actions)))
            st.success(f"Flow created! ID: {result.get('flow_id')}")
            st.json(result)
            st.cache_data.clear()
        except Exception as e:
            st.error(f"Error: {e}")

# ── Templates ─────────────────────────────────────────────────────────────────
st.subheader("Quick Templates")
templates = {
    "compliance_reminder": ("🔔 Compliance Reminder", "Weekly reminder to employees with overdue required training"),
    "completion_notification": ("✅ Completion Notification", "Notify manager when employee completes a course"),
    "weekly_report_delivery": ("📧 Weekly Report Delivery", "Email weekly learning summary to department heads"),
    "skill_gap_alert": ("⚠️ Skill Gap Alert", "Alert L&D team when skill gaps exceed threshold"),
}
cols = st.columns(4)
for i, (tid, (label, desc)) in enumerate(templates.items()):
    with cols[i]:
        st.markdown(f"**{label}**\n\n{desc}")
        if st.button(f"Use template", key=f"tpl_{tid}"):
            try:
                from mcp_servers.automate_server import get_flow_from_template
                result = json.loads(get_flow_from_template(tid))
                st.success(f"Flow created from template! ID: {result.get('flow_id')}")
                st.cache_data.clear()
            except Exception as e:
                st.error(f"Error: {e}")

st.divider()

# ── Saved flows ───────────────────────────────────────────────────────────────
st.subheader("Saved Flows")

@st.cache_data(ttl=30)
def load_flows():
    if not DB_PATH.exists():
        return []
    conn = sqlite3.connect(DB_PATH)
    conn.row_factory = sqlite3.Row
    rows = conn.execute("SELECT * FROM generated_flows ORDER BY created_at DESC").fetchall()
    conn.close()
    return [dict(r) for r in rows]

flows = load_flows()

if not flows:
    st.info("No flows yet. Use the templates above or ask the Chat Agent to create one.")
else:
    for flow in flows:
        with st.expander(f"**{flow['flow_name']}** — {flow['status'].upper()} | {flow['trigger_type']}", expanded=False):
            st.markdown(f"**Description:** {flow['description']}")
            st.markdown(f"**Created:** {flow['created_at']}")
            col1, col2 = st.columns([1, 4])
            with col1:
                if st.button("▶ Run Flow", key=f"run_{flow['id']}"):
                    try:
                        from mcp_servers.automate_server import trigger_flow
                        result = json.loads(trigger_flow(flow["id"]))
                        st.success(f"Triggered! Run ID: {result.get('run_id')}")
                    except Exception as e:
                        st.error(f"Error: {e}")
            with col2:
                try:
                    flow_def = json.loads(flow["flow_json"])
                    st.json(flow_def)
                except Exception:
                    st.code(flow["flow_json"])
